### PR TITLE
Add dynamic host name to Header view

### PR DESCRIPTION
**Pull request by K-Ko**

### CODE REVIEW

**Comment by ColinWaddell** [comment]
Just having a little look at the update to Header. I can see the benefit if you're using this on multiple devices so you can see at a glace which you are looking at. On the one hand I worry about how this will look aesthetically on different systems. On the other - this software isn't just limited to an RPi so I can see why it may be silly to have "Raspberry Pi Status" in the title.

I've got no idea about what platforms this is being ran on - my guess is that majority are RPis. Unless it turned out that a huge number of people were running this on alternative hardware I'd be keen to keep the tag-line "Raspberry Pi Status" however I wouldn't be against sticking the hostname somewhere in the title name.

If you could maybe expand on your thoughts on tweaking the title area @K-Ko and how you came to make this change?

Thanks again for your time!

**Comment by K-Ko** [comment]
It just remove the limit to Raspberry in header, only Currant Pi is then Raspi centered:

2016-05-18 11_28_57-currant pi - raspberry pi status

2016-05-18 11_29_10-currant pi - raspberry pi status

and so on, I have some Raspi on the run...

**Comment by K-Ko** [comment]
May be, make the header configurable, with parameter for "Currant Pi" and the Raspi logo?!
But then ist not zero config anymore :-(

**Comment by ColinWaddell** [comment]
Hey. I've been playing around with this pull-request tonight. I'm into having the hostname near the top of the page. I'm going to mess around and see if there's a tidy way I can keep the sub-heading as it is but perhaps re-jig the logo to include the hostname over that side.

Once I've got a mock-up together I'll drop a screenshot in here and you can let me know what you think.

**Comment by ColinWaddell** [comment]
What do you think?

image

**Comment by ColinWaddell** [comment]
I've created a branch for you to checkout my attempt: [banner-servername](https://github.com/ColinWaddell/CurrantPi/tree/banner-servername)

**Comment by K-Ko** [comment]
Looks good :+1: 

zwischenablage01

**Comment by K-Ko** [comment]
Any news?

**Comment by ColinWaddell** [comment]
Hey @K-Ko 

so sorry I've not been keeping on top of this. Had an unfortunate dose of real life recently which has kept me AFK.

I've got a pure CSS solution for your other pull-request in the pipeline that I can probably get merged in the next week. This pull-request I've not had a chance to really get my teeth into yet.

I still don't think we've cracked the perfect solution but I'm more than happy to keep plugging away once I've the time.

Hopefully in the next couple of weeks things should calm down here and I can get back to a bit of recreational programming again: aka bliss.

I'll be in touch!

**Comment by K-Ko** [comment]
Any news?

**Comment by ColinWaddell** [comment]
Hey @K-Ko 

I've just pushed some changes to branch banner-hostname.

Done some CSS trickery to get it so that the logo right aligns but spaces out for the hostname as the text increases in width.

Let me know what you think and I'll merge it with master.

Cheers!

**Comment by ColinWaddell** [comment]
I decided to just batter in and merge this. I'm sure if it looks bad somewhere someone will let me know!

**Pull request merged**
