### PR TITLE
Add load average & rearrange html

### PR DESCRIPTION
**Pull request by mephissto**
Add load average & rearrange html

### CODE REVIEW

**Comment by ColinWaddell** [comment]
Wow. Cheers dude. I'll get this looked at tomorrow night once I'm behind my
computer. Thanks again!

**Comment by mephissto** [comment]
No problem, I was inspired :)
I'm preparing another pull request right now :D

**Comment by mephissto** [comment]
I merged my branch too soon on my master, let me know if you want me to remove the font awesome commits from this request

**Comment by ColinWaddell** [comment]
Don't worry, leave them in. I'm going to spend a few hours tonight doing a
bit of a re-write to split up index.php anyway as it's getting a little
large. I can sweep up your font-awesome commits as I'm merging branches.

Again, cheers for your help.

## 

Colin
colinwaddell.com http://www.colinwaddell.com

**Comment by ColinWaddell** [comment]
Ok. So first job of the evening is out the way. I've merged your code and tweaked the header.

**Comment by mephissto** [comment]
Great :) I updated the project on my server and it looks nice.

**Pull request merged**
