### PR TITLE
Remove tmpfs file systems from Storage module

### PR DESCRIPTION
**Pull request by K-Ko**

### CODE REVIEW

**Comment by ColinWaddell** [comment]
Good call. I'll get this merged in the next couple of days when I've got time for some recreational work.

Cheers for your help @K-Ko

**Comment by ColinWaddell** [comment]
Just wondering if others who have helped contribute have any input on this pull-request?

@mtantawy @mephissto @Krettis 

I'm uncertain of peoples interest in usage of `tmpfs` in the storage section. On the one hand if people are interested in storage they're probably wondering how much their SD-Card/HDs have available; on the other, I can see the use in having these available if they're doing something like this: [Reduce writes to the Raspberry Pi SD card](http://oils-of-life.com/blog/linux/reduce-writes-to-the-raspberry-pi-sd-card/)

Enabling/disabling display of `tmpfs` could be added as a configuration option but I'm not entirely keen of a move in that direction.

Any input would be great. Cheers everyone!

---

Here's a screenshot of the @K-Ko pull-request in action

image

**Comment by K-Ko** [comment]
Mine is here: https://github.com/ColinWaddell/CurrantPi/pull/41#issuecomment-222973402

**Comment by mtantawy** [comment]
How about keeping them but making these rows in the table collapsed for example?

**Comment by K-Ko** [comment]
collapsed :+1:

**Comment by ColinWaddell** [comment]
Submitting my example of how to handle the tempfs entries. I've popped it in this branch: [tempfs](/ColinWaddell/CurrantPi/tree/tempfs)

It's hides a second table containing the tempfs and reveals it using a button. All implemented in CSS. Modifies the api such that the storage entries are split into two arrays: regular storage and hidden.

---

image

---

image

**Comment by K-Ko** [comment]
:+1:  Looks good

**Comment by K-Ko** [comment]
Any news?

**Comment by xela-zone** [comment]
any more news?

**Comment by ColinWaddell** [comment]
Howdy @mralext20 @K-Ko 

I've merged this update with master but I'm sans RPi to test it on. Would someone be as kind as to check nothing untoward is going on?

Cheers!

**Pull request merged**
