### PR TITLE
New colors for membars

### PR DESCRIPTION
**Pull request by mephissto**
Hello,

Here is a proposal for colors membar :)

These colors were choosen in Google Material Design colors : https://www.google.com/design/spec/style/color.html#color-color-palette

As always here is a preview : http://info.msl.re/

### CODE REVIEW

**Comment by ColinWaddell** [comment]
Spent the night playing around with this and went for something a bit more toned down. I've applied the style across the whole thing. Let me know what you think: 9eb733f5dd506f4b57e0db432caa8ec7aa0299e3

**Comment by mephissto** [comment]
Hello,

I've updated your app on my server, and the colors seems to be washed out.

Anyway it's just my feeling :)

**Comment by ColinWaddell** [comment]
Cheers for your input dude.

It's tricky trying to find a simple collection that can be used throughout
the page without being overpowering, but feeling correct in context (ie.
Red for Used).

I need to check out this scheme on a few more screens before I settled on a
final set of colours.

I think the muted palette is here to stay, but I agree it may require some
tweaking still.

**Comment by mephissto** [comment]
I tested it on my MacBook pro retina and it's on it that the colors seemed washed out.

**Comment by ColinWaddell** [comment]
Perfect, cheers.

**Comment by ColinWaddell** [comment]
Howdy @mephissto 

Took your advice and have brightened things up a little 208c6d50644bfc4948fa85ed17bea5727ea4ec45

Tweaked the red and I think that's done the trick.

Contextually it made sense having that red to represent "Used" throughout the page but it was a bit overpowering. So I've used green from Cache, it sits quite nice.

Let me know what you think. The more eyes looking at this the better :eyes:

**Comment by ColinWaddell** [comment]
Live demo here: http://ukube.colinwaddell.com/rpiinfo/

**Comment by mephissto** [comment]
Hello,

It's better now.

And I agree about the Cache color for storage, it's better.

Nice job :)

**Comment by ColinWaddell** [comment]
No worries. After a day's coding at work followed by an evenings picking
colours I think I'd broken my eyes.

Cheers again for calling out it being too faded - constructive criticism
can be hard to give!

## 

Colin
colinwaddell.com http://www.colinwaddell.com

**Pull request closed without merging**
