### PR TITLE
Refactoring to MVC

### PR DESCRIPTION
**Pull request by sio-iago**
This is my contribution to this repository.
My refactoring to MVC pattern, using Slim Framework and Composer.

Please consider it.

### CODE REVIEW

**Comment by sio-iago** [comment]
About the footer, the template engine the following comment:

``` php
{#

Old Script

<p>
    <?php
    $name_full = shell_exec('cat /proc/cpuinfo | grep name | head -1');
    $name = explode (': ', $name_full);
    echo $name[1];
  ?>
</p>

#}
```

We can put this script on the NativeInvoker and send to the template or put the script in another place (like another page section as Memory, Storage,...).

**Comment by dougsta** [comment]
The native PHP was pretty easy to follow from a non-PHP person like me, whereas the slim framework seems unnecessarily complex.  The audience for this dashboard includes people with a vast range of skills and expertise:  I would advocate for keeping it as simple as possible.

**Comment by ColinWaddell** [comment]
Wow. Thanks @sio-iago - that's a huge amount of work. I'll check out this pull-request hopefully tonight when I'm home.

I'm currently in two minds about coding this up 'properly' using a framework such as slim. On the one hand, if this project was just for me or a professional job then I'd 100% be abstracting everything as much as possible. I even caught myself early in the project writing Classes to handle the tables and progress-bars.

I stopped myself though when, as pointed out by @dougsta, I realised the target audience for this probably just wants to unpack the repo and tinker without having to deal with design patterns and abstraction.

I'm very keen to see what you've produced though, I've not playing with Slim yet and have been considering using it for my weather site [Taps Aff](http://taps-aff.co.uk) as it's current a horror show of badly implemented KissMVC.

**Comment by sio-iago** [comment]
I respect both opinions and thinking about what @dougsta said, it makes sense to keep simple.

On the other hand, if you want to grow the project to do more complex stuff, I highly recommend using a framework. Slim Framework is a micro framework, which means is not as complex as Symfony, Laravel or ZF2. I use Slim in most of my projects because of it's simplicity and low learning curve.

I'd like to ask to add my pull-request as a branch, maybe, in case you or someone else wants to work with the project using the MVC pattern.

Thank you.

**Comment by ColinWaddell** [comment]
Absolutely @sio-iago. I'll get an Slim branch sorted. I'm planning on writing up proper documentation this week and I'll include notes about the Slim implementation in there also.

**Comment by ColinWaddell** [comment]
I've created a branch for the work you started @sio-iago 24ff5940bc77e90339697444e3bba6effbda7b04

**Pull request closed without merging**
