### PR TITLE
Added Public API Controller

### PR DESCRIPTION
**Pull request by sio-iago**
Hello Colin! Iago here again.

I was watching the official repo and someone is with a pull-request for an API. Since I already have codes to JSON API using my slim version, I'm adding here the API approach.

If you could take a look and merge to the slimmvc branch would be great.

Thanks.

### CODE REVIEW

**Comment by ColinWaddell** [comment]
Cool. Not had a chance to catch up with pull requests in a week as I've
been savaged by the cold, but should have some time tonight to go through
everything. I'll be back in contact once I'm up to speed

**Comment by ColinWaddell** [comment]
Also, @sio-iago 

I'd be interested if you had any thoughts on the comment I made [here](https://github.com/ColinWaddell/CurrantPi/pull/30#issuecomment-175788557) about the direction of future development.

Any feedback would be great, cheers.

**Comment by ColinWaddell** [comment]
Hey.

Pushed your changes.

If you find a moment you should add a couple of lines to the README to show how to get composer.phar running.

Cheers again for your help! :trophy:

**Comment by sio-iago** [comment]
Thanks dude. I'm glad to help you.
I'll check the direction of future development and see what I could do to help.

Cheers!

**Pull request merged**
