### PR TITLE
Tweak membar

### PR DESCRIPTION
**Pull request by mephissto**
I've tweaked and fixed some variables.

Also, you were not using the right value from **free** for the ram used, I changed that.

Also, I changed the info displayed about the RAM to display free and used per total RAM.

And I narrow the number of informating displayed in the memory bar to only show free & used.

As always, feel free to change what you in this code :)

Regards

### CODE REVIEW

**Comment by mephissto** [comment]
I was also thinking, if you want to display more information / bar about RAM, you should add more bar as it might not be really readable in only one bar, but it "breaks" the page style.

**Comment by ColinWaddell** [comment]
Cool. I've a couple of hours set aside this afternoon for some recreational-programming. I'll get this pull request dealt with then.

**Comment by ColinWaddell** [comment]
So I've been looking at your pull request and I think you've fallen into the same trap as I did first time around. When calculating the amount of free RAM you should be adjusting for the amount taken by buffers/cache. This RAM is actually still available to applications/kernel and can be allocated at any time.

[This reddit comment](https://www.reddit.com/r/raspberry_pi/comments/3zs89i/created_a_webinterface_to_keep_on_eye_on_how_my/cypda87?context=4) put me onto the error, and [this serverfault](http://serverfault.com/questions/85470/meaning-of-the-buffers-cache-line-in-the-output-of-free) page helped clear things up a lot too. 

If you want to confirm where I'm getting my figures from check [this line](https://github.com/ColinWaddell/RPi-Board-Info/commit/b48bf2d2d30d61fdd188b87710a484aa29a36aa0?diff=unified#diff-9bd624f4c096b3c6d8c1df017c473317R6) and you see they all add up to a value very very slightly under the total amount of RAM available. The last tiny bit that's inaccessible is used by the bootloader.

I'm happy to be convinced otherwise though, between being at work and then writing this I think I was onto about my 20th hour staring at a screen so I there's a chance I've misunderstood along the way.

**Comment by mephissto** [comment]
Oh ok, I've probably made a mistake, I'll look at this later today or maybe tomorrow and I'll correct my pull request :) 

Thank you for your comment ^^

**Comment by ColinWaddell** [comment]
I've pushed quite a lot of changes to the memory bar so I'm just going to close this pull-request as it currently stands.

If you want to get stuck into tweaking the bar I'd recommend updating your repo.

Not 100% convinced about the colours I've chosen, but I think it's getting across the information is a tidy manner.

**Comment by mephissto** [comment]
No problem, I've updated the app on my server and it looks great. 

Great job :)

**Pull request closed without merging**
