### PR TITLE
Api

### PR DESCRIPTION
**Pull request by mtantawy**
I admire the effort done to grab all such server info and thought that it'd be a good idea if we can split the script that gets the info and the script(s) that display the info for the user, that way the project should be cleaner and also that would easily allow us to provide a simple API.

The API is quite useful for example if someone owns more than one RPi and wants to keep an eye on all of them at once, also allows anyone to make use of only pieces of info he needs to monitor.

Also, having such API, allows to have a self-updating web age by issuing AJAX requests and then simply update the view, thus way the user can monitor the RPi in real time instead of having to refresh every now and then.

Later on, we can enhance the API and AJAX requests to send warnings for certain events like spikes in CPU load or having low storage for example.

### CODE REVIEW

**Comment by ColinWaddell** [comment]
Hey Mahmoud,

Cheers for submitting this. I'm AFK just now but will have some time
tomorrow evening to have a look and give you a proper reply.

**Comment by mtantawy** [comment]
Sounds good, looking forward! :)

**Comment by ColinWaddell** [comment]
Howdy @mtantawy 

Had a chance to go through your plan.

You know, I've actually went through the motions of doing this before. In an ideal world I'd be keen on completely separating the model and the view. [There was even a wee discussion on the matter here.](https://github.com/ColinWaddell/CurrantPi/pull/13#issuecomment-170334675)

I like your implementation though. I think if there was a method of arranging the code so that it was very very clear to people new to programming where the information was coming from then I'd be up for rearranging CurrantPi to suit. 

I'm going to copy and paste a chunk of the Contributing section to anyone coming across this comment:

> I'd like the code to feel accessible enough that anyone interested can play with it. People new to programming shouldn't have to deal with fancy design patterns and abstractions. I'd like to keep the code simple but not stupid, clean and as readable as possible.
> 
> Code should be simple enough that any eager beginner can follow it.

So. If you don't mind then I'm not going to merge your pull request just now - but I'm not closing it either. It's definitely worth exploring. Here's my thoughts on the matter and I'd love your feedback:
- Having a file structure where each chunk of model was named the same as it's view. Currently you've been adding the model code into `lib/server_info.php`. This could be split up into separate files which align with each view element in `content/`.
  
  Perhaps these should live in a separate directory from `lib`. Going against MVC tradition perhaps it could be arranged something like `content/memory/display.php` `content/memory/data.php`. Not that I'm completely keen on those filenames, it's just I'm trying to keep it clear what's happening to the uninitiated. 
- Despite appearances I'm not keen on using global variables. Perhaps placing each data source in its own function and doing something like `$memory_data = Memory()` from within the view, then using `$memory_data->whatever` throughout the view.
  
  That would also simplify creating an Object to represent the entire server's info to pass back as json.
- I'm trying to avoid any js in this for a couple of reasons. I'd hate to be dependant on some json being decoded to see what's going on. I access Currant Pi though links2 pretty regularly and at the moment it works great. Wouldn't want that to change. Second reason is it's another programming language for new users to grasp.

If I think of anything else I'll give you a shout in this thread. 

Hope you get where I'm coming from. I think if there's a clean way to execute your plan then I'm up for entertaining it. Be sure to let me know what you think and keep me posted on any development you make. If you drop me a message in this thread and I'll have a look when I get a chance. I generally have one night a week to properly get my teeth into this sort of thing.

**Comment by mtantawy** [comment]
Hey,

Let me try and make some changes and update you again soon.

**Comment by mtantawy** [comment]
I re-structured most of the modifications.

**Comment by ColinWaddell** [comment]
Cool. I'll hopefully have a chance to get through these updates tomorrow
night. If not it might take me a couple of days.

Cheers for your help Mahmoud

## 

Colin
colinwaddell.com http://www.colinwaddell.com

**Comment by mtantawy** [comment]
Hey man, wondering if there are any updates?

**Comment by ColinWaddell** [comment]
Don't worry, haven't forgot about you.

Not had a chance to catch up with pull requests in a week as I've been
savaged by the cold, but should have some time tonight to go through
everything. I'll be back in contact once I'm up to speed

**Comment by ColinWaddell** [comment]
Duuuuuuude - This is amazing! 

Really sorry it's taken me so long to have a look at this. You've put in a tonne of work.

Almost certainly going to pull all this. I want to spend a little time going through all the code though and having a little play myself.

:trophy:

**Comment by ColinWaddell** [comment]
Hey. I think that's me done for the night.

Pulled your changes into master.

I made a bunch of tweaks, as I couldn't help myself. Here's the rough overview:
- Personal preference - moved everything to 2-space indenting. If you aren't keen, just be glad it isn't tabs.
- That chunk of code in `api.php` to load up each of those modules is very clever is very clever. I added some comments to make it clear how to use it.
- I renamed all the view.php file to bring them inline with the name of the `[whatever]Data.php` file in the same directory.
- Made up a string helper class `StringHelpers.php` and made all the functions which were previously in `string_helpers.php` into static methods. I renamed them to fit with your `methodName` formatting.

Cheers again for the work you put in. It's very much appreciated!

**Comment by mtantawy** [comment]
Sounds great!

**Pull request merged**
