### PR TITLE
API changes

### PR DESCRIPTION
**Pull request by Krettis**
- Made a few minor changed for more cleaner content
- Ask for just one source instead of getting everything

Unfortunately it's not possible to do something with the .htaccess so had to build something in the api.php itself.

### CODE REVIEW

**Comment by ColinWaddell** [comment]
Hey @Krettis 

Thanks for your pull-requests. I've already merged the one regarding the footer updates: #34 

I'm just looking through this one just now and all looks good. I've one request though - please let me know what you think and whether you're happy to make the change yourself.

So you've got it set that visiting `http://myserver/api.php/<module>` will load just the json for `module`. How would you feel about extending this so that you can concatenate requests? Perhaps something like `http://myserver/api.php/<module 1>|<module 2>|<etc>`. That way a single json request can be used to grab a selected list of sources. I've used pipe `|` in my example to separate modules as I think it's quite clear what's going on, the other option would be a forward slash `/` but I think that implies a hierarchy that doesn't exist.

Very happy with the quality of your 2 pull requests - many thanks for spending the time looking at this :trophy:

**Comment by Krettis** [comment]
Hello @ColinWaddell,

Thanks for accepting the pull-request! I didn't want to do a lot of changes on the api because you mentioned you want it to be simple for newcomers. The change I made is just enough for a single php-file. 

I have a question surrounding the api. Do you want it to be a real rest-api? Or more a php-file with some simple request? Because my solution nor yours wouldn't be really the way to go. I don't think splitting it in pipes is really accepted either. The real solution would be more the way to go with a route like this:

```
 GET http://myserver/api.php/v1/source?q=<MODULE-A>,<MODULE-B>,<MODULE-C>
```

or

```
 GET http://myserver/api.php/v1/source
 HEADER-ACCEPT Content-type: application/foo+json;<MODULE>
```

I know there are some small little frameworks working with this which you could implement real quick after a few pulls. The advantage is that it still can look simple and you'll get decent error headers when something goes wrong. It doesn't have to be complicated only you'll set the road for making it easier to provide some extra features. (like PUT http://myserver/api.php/v1/camera HEADER params: take picture:true or something)

Also working with v1/v2/v3 will be a lot better working with an api so people don't necesarely have to update their own code if there is a neat update available on the index.php, because of backwards compatibility.

But I don't know how serious you want this. 

Another question: Will there at least be a psr2-standard in the future?

**Comment by ColinWaddell** [comment]
PSR2 sounds great. Thanks for pointing it out, I'm a recreational php user
and was totally unaware of it.

As for your other info... first cheers for reading the bit about trying to
keep the code simple. Hope you see where I'm coming from. Thing is, if
people want a feature packed app rather than a starter project then I'd be
up for entertaining it. I just don't know where the interest lies.

I think it's maybe getting close to time to releasing this app as CurrantPi
v1 and seeing who wants to use it.

Major caveat would be that the app can just get cloned/unzipped and it just
works. No messing.

Any input would be great, feel free to raise an issue if you'd like a place
to discuss ideas/suggestions you may have about future developments.

**Comment by ColinWaddell** [comment]
I know I've barely answered any of your questions there! I'm AFK just now
but will come back to your other points in the next couple of days.

**Comment by Krettis** [comment]
>  I think it's maybe getting close to time to releasing this app as CurrantPi v1 and seeing who wants to use it.

Just a quick remark; using versions for the api doesn't have much to do with the version for the app itself. It's more of an indicator to make sure nothing will break when new features arrive for the api itself.

I thought about it last day and I think if you really want to do a serious api , it's better to do it an a separate repo. So for now even the use of a cool small framework right of the box would be ill-advised. But I can imagine having a real cool API could be really powerful. I've searched on github for other possible API's centered around the raspberry system itself, but can't find much useful.

It's a bit of a question how big this project will grow :+1: 
To keep it simple, my suggestion is to make this route:

```
GET http://myserver/api.php/<MODULE-A>,<MODULE-B>,<MODULE-C>
```

It's not really a rest-api, but the best way for now.

**Comment by ColinWaddell** [comment]
Agreed. I think having an API available would be a great feature, but its
implementation shouldn't interfere with the way CurrantPi is currently being
developed.

So, for now I think pulling the php in line with the coding standard you
recommended will be my next big job.

Have you any interest in updating your pull-request to match the simple
method you specified above? I'm more than happy to tackle it myself, it
just might take me a week to get around to it.

## 

Colin
colinwaddell.com http://www.colinwaddell.com

**Comment by Krettis** [comment]
Hopefully this commit is enough :)

**Comment by ColinWaddell** [comment]
Cool - I'll get it merged this week. Cheers for your time!

**Comment by Krettis** [comment]
Great! You're welcome.

**Comment by ColinWaddell** [comment]
Hey @Krettis just another wee thanks for your input. I've raised an issue to myself to get started on refactoring for PSR2. Have a great weekend.

**Pull request merged**
